name: Workflows, Jobs, and Steps


on:
  workflow_dispatch:

jobs:
  self-hosted-job-1:
   runs-on: self-hosted-job-1
   steps:
    - run: echo "my first self hosted runner"

  self-hosted-job-2:
    runs-on: ubuntu-24-04
    needs:
      - self-hosted-job-1
    steps:
     - run: echo "running after  self-hosted-job-1 sucessfull" 
